import type {
	ProviderConfig,
	ProviderModelConfig,
} from "@mariozechner/pi-coding-agent";
import type { IntegrationProviderPayloadRewrite } from "./request_rewrite.ts";

type WarnFn = (message: string) => void;

export type IntegrationProviderInfo = {
	config: ProviderConfig;
	// Exact model aliases generated by this extension to preserve duplicate names.
	modelAliases?: ReadonlyMap<string, string>;
	// Exact generated model ids that need ChatGPT /codex/responses payload shaping.
	chatGPTModelIds?: ReadonlySet<string>;
	// Base URLs this extension registered for the integration provider.
	baseUrls: ReadonlySet<string>;
};

export interface CatalogCompat {
	supportsDeveloperRole?: boolean;
	maxTokensField?: string;
	supportsReasoningEffort?: boolean;
	thinkingFormat?: string;
	cacheControlFormat?: string;
}

export interface CatalogModel {
	id: string;
	name?: string;
	type?: string;
	reasoning?: boolean;
	input?: ("text" | "image")[];
	contextWindow?: number;
	maxTokens?: number;
	cost: {
		input: number;
		output: number;
		cacheRead: number;
		cacheWrite: number;
	};
	compat?: CatalogCompat;
	thinkingLevelMap?: Partial<
		Record<
			"off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max",
			string | null
		>
	>;
}

export interface CatalogProvider {
	id: string;
	path: string;
	api?: string;
	models: CatalogModel[];
}

export interface Catalog {
	schemaVersion: number;
	providers: CatalogProvider[];
}

interface ReflectionIntegration {
	name?: string;
	type?: string;
	team?: boolean;
	help?: string;
}

interface ReflectionIntegrationsResponse {
	integrations?: ReflectionIntegration[];
}

interface IntegrationModelArchitecture {
	input_modalities?: string[];
	output_modalities?: string[];
}

interface IntegrationModelLimits {
	context_window?: number;
	max_output_tokens?: number;
}

interface IntegrationModelExeDev {
	mode?: string;
}

// Unnormalized passthrough of the provider's own model record. commandai leaves
// `limits` empty for every model but reports the window here.
interface IntegrationModelUpstream {
	context_length?: number;
}

interface IntegrationModel {
	id: string;
	name?: string;
	provider: string;
	native_id?: string;
	apis?: string[];
	architecture?: IntegrationModelArchitecture;
	limits?: IntegrationModelLimits;
	upstream?: IntegrationModelUpstream;
	exe_dev?: IntegrationModelExeDev;
}

interface IntegrationCatalog {
	schema_version: number;
	models: IntegrationModel[];
}

export type DiscoveredIntegration = {
	name: string;
	baseURL: string;
	catalog?: IntegrationCatalog;
};

type CompatBag = {
	supportsDeveloperRole?: boolean;
	supportsReasoningEffort?: boolean;
	maxTokensField?: "max_tokens" | "max_completion_tokens";
	thinkingFormat?:
		| "openai"
		| "openrouter"
		| "deepseek"
		| "zai"
		| "qwen"
		| "qwen-chat-template";
	cacheControlFormat?: "anthropic";
};

export type JSONFetcher = (url: string) => Promise<unknown | undefined>;

// Both the integration catalog and the bundled pricing sidecar currently use
// schema version 1. Unknown shapes are ignored rather than becoming routes.
export const SCHEMA_VERSION = 1;

const KNOWN_THINKING_FORMATS: ReadonlySet<string> = new Set([
	"openai",
	"openrouter",
	"deepseek",
	"zai",
	"qwen",
	"qwen-chat-template",
]);
const KNOWN_MAX_TOKENS_FIELDS: ReadonlySet<string> = new Set([
	"max_tokens",
	"max_completion_tokens",
]);
const KNOWN_CACHE_CONTROL_FORMATS: ReadonlySet<string> = new Set(["anthropic"]);

export function validCatalog(cat: unknown): cat is Catalog {
	if (!cat || typeof cat !== "object") return false;
	const c = cat as Catalog;
	if (c.schemaVersion !== SCHEMA_VERSION) return false;
	if (!Array.isArray(c.providers) || c.providers.length === 0) return false;
	return true;
}

function validIntegrationCatalog(cat: unknown): cat is IntegrationCatalog {
	if (!cat || typeof cat !== "object") return false;
	const c = cat as IntegrationCatalog;
	if (c.schema_version !== SCHEMA_VERSION) return false;
	if (!Array.isArray(c.models)) return false;
	return true;
}

export async function fetchJSONWithTimeout(
	url: string,
	timeoutMS: number,
): Promise<unknown | undefined> {
	const res = await fetch(url, { signal: AbortSignal.timeout(timeoutMS) });
	if (!res.ok) return undefined;
	return (await res.json()) as unknown;
}

function reflectionLLMIntegrations(
	reflection: unknown,
): ReflectionIntegration[] | undefined {
	const integrations = (
		reflection as ReflectionIntegrationsResponse | undefined
	)?.integrations;
	if (!Array.isArray(integrations)) return undefined;
	return integrations.filter(
		(integration) =>
			integration.type === "llm" &&
			typeof integration.name === "string" &&
			integration.name.length > 0,
	);
}

const RETRY_DELAYS_MS = [250, 750, 2000];

async function fetchWithRetries(
	url: string,
	fetchJSON: JSONFetcher,
): Promise<unknown | undefined> {
	for (let attempt = 0; ; attempt++) {
		try {
			const value = await fetchJSON(url);
			if (value !== undefined || attempt === RETRY_DELAYS_MS.length)
				return value;
		} catch (err) {
			if (attempt === RETRY_DELAYS_MS.length) throw err;
		}
		await new Promise((resolve) =>
			setTimeout(resolve, RETRY_DELAYS_MS[attempt]),
		);
	}
}

async function fetchReflectionIntegrations(
	url: string,
	fetchJSON: JSONFetcher,
	warn: WarnFn,
): Promise<ReflectionIntegration[]> {
	let integrations: ReflectionIntegration[] | undefined;
	try {
		const reflection = await fetchWithRetries(url, fetchJSON);
		integrations = reflectionLLMIntegrations(reflection);
		if (!integrations)
			throw new Error(`${url} returned unrecognized reflection shape`);
	} catch (err) {
		warn(
			`[pi-exe-dev] LLM integration reflection fetch failed: ${(err as Error).message}`,
		);
		return [];
	}
	return integrations;
}

function defaultIntegrationBaseURL(integration: ReflectionIntegration): string {
	const name = integration.name as string;
	return integration.team === true
		? `https://${name}.team.exe.xyz`
		: `https://${name}.int.exe.xyz`;
}

function integrationBaseURLCandidates(
	integration: ReflectionIntegration,
): string[] {
	const candidates: string[] = [];
	const add = (baseURL: string) => {
		if (!candidates.includes(baseURL)) candidates.push(baseURL);
	};

	for (const match of integration.help?.matchAll(/https?:\/\/[^\s'"`]+/g) ??
		[]) {
		try {
			const url = new URL(match[0]);
			if (
				url.hostname.endsWith(".int.exe.xyz") ||
				url.hostname.endsWith(".team.exe.xyz")
			) {
				add(url.origin);
			}
		} catch {
			// Ignore prose that looked like a URL but was not parseable.
		}
	}

	if (integration.name) {
		if (integration.team === true) {
			add(`https://${integration.name}.team.exe.xyz`);
		} else {
			add(`https://${integration.name}.int.exe.xyz`);
		}
	}
	return candidates;
}

function firstAggregateErrorMessage(err: unknown): string {
	if (err instanceof AggregateError && err.errors.length > 0) {
		return (err.errors[0] as Error).message;
	}
	return (err as Error).message;
}

async function fetchIntegrationCatalog(
	integration: ReflectionIntegration,
	fetchJSON: JSONFetcher,
	warn: WarnFn,
): Promise<DiscoveredIntegration> {
	const name = integration.name as string;
	const candidates = integrationBaseURLCandidates(integration);
	if (candidates.length === 0)
		return { name, baseURL: defaultIntegrationBaseURL(integration) };

	try {
		return await Promise.any(
			candidates.map(async (baseURL) => {
				const catalog = await fetchWithRetries(
					`${baseURL}/models.json`,
					fetchJSON,
				);
				if (!validIntegrationCatalog(catalog)) {
					throw new Error(
						`${baseURL}/models.json returned unrecognized catalog shape`,
					);
				}
				return { name, baseURL, catalog };
			}),
		);
	} catch (err) {
		warn(
			`[pi-exe-dev] LLM integration ${name} models.json fetch failed: ${firstAggregateErrorMessage(err)}`,
		);
		return { name, baseURL: defaultIntegrationBaseURL(integration) };
	}
}

export async function discoverIntegrationCatalogs(
	reflectionURL: string,
	fetchJSON: JSONFetcher,
	warn: WarnFn = console.warn,
): Promise<{ found: boolean; integrations: DiscoveredIntegration[] }> {
	const llmIntegrations = await fetchReflectionIntegrations(
		reflectionURL,
		fetchJSON,
		warn,
	);
	if (llmIntegrations.length === 0) return { found: false, integrations: [] };
	const integrations = await Promise.all(
		llmIntegrations.map((integration) =>
			fetchIntegrationCatalog(integration, fetchJSON, warn),
		),
	);
	return { found: true, integrations };
}

type IntegrationAPIAdapter = {
	catalogAPI: string;
	piAPI: NonNullable<ProviderConfig["api"]>;
	basePathSuffix: "" | "/v1";
};

// Protocol priority is independent of provider identity. New providers and
// BYOP entries work automatically when their catalog models advertise a wire
// protocol Pi already supports.
const INTEGRATION_API_ADAPTERS: readonly IntegrationAPIAdapter[] = [
	{
		catalogAPI: "openai_responses",
		piAPI: "openai-responses",
		basePathSuffix: "/v1",
	},
	{
		catalogAPI: "anthropic_messages",
		piAPI: "anthropic-messages",
		basePathSuffix: "",
	},
	{
		catalogAPI: "openai_chat",
		piAPI: "openai-completions",
		basePathSuffix: "/v1",
	},
];

function integrationAPIAdapter(
	model: IntegrationModel,
): IntegrationAPIAdapter | undefined {
	const apis = new Set(model.apis ?? []);
	return INTEGRATION_API_ADAPTERS.find((adapter) =>
		apis.has(adapter.catalogAPI),
	);
}

function validIntegrationProviderID(provider: string): boolean {
	return provider !== "accounts" && /^[a-z0-9_-]+$/.test(provider);
}

function integrationProviderBaseURL(
	baseURL: string,
	provider: string,
	adapter: IntegrationAPIAdapter,
): string {
	return `${baseURL.replace(/\/+$/, "")}/${provider}${adapter.basePathSuffix}`;
}

function integrationModelID(model: IntegrationModel): string | undefined {
	const id = model.native_id || model.id;
	return typeof id === "string" && id.length > 0 ? id : undefined;
}

function integrationAliasModelID(
	modelID: string,
	integrationName: string,
): string {
	return `${modelID}@${integrationName}`;
}

function inputModalities(
	model: IntegrationModel,
	fallback: CatalogModel | undefined,
): ("text" | "image")[] {
	const out = (model.architecture?.input_modalities ?? []).filter(
		(input): input is "text" | "image" => input === "text" || input === "image",
	);
	if (out.length > 0) return out;
	if (fallback?.input?.length) return fallback.input;
	return ["text"];
}

function costCatalogIndex(
	catalog: Catalog | undefined,
): Map<string, CatalogModel> {
	const out = new Map<string, CatalogModel>();
	if (!catalog) return out;
	for (const provider of catalog.providers) {
		for (const model of provider.models) {
			out.set(`${provider.id}\0${model.id}`, model);
		}
	}
	return out;
}

// A catalog entry that exists only to carry limits still leaves usage cost at
// zero, so it must not silence the pricing warning.
function hasPricing(fallback: CatalogModel | undefined): boolean {
	const cost = fallback?.cost;
	if (!cost) return false;
	return Boolean(cost.input || cost.output || cost.cacheRead || cost.cacheWrite);
}

function fallbackCatalogModel(
	costs: Map<string, CatalogModel>,
	provider: string,
	modelID: string,
	requestID: string,
): CatalogModel | undefined {
	return (
		costs.get(`${provider}\0${modelID}`) ??
		costs.get(`${provider}\0${requestID}`)
	);
}

const GATEWAY_GPT56_THINKING_LEVEL_MAP = {
	off: "none",
	minimal: "minimal",
	low: "low",
	medium: "medium",
	high: "high",
	xhigh: "xhigh",
	max: "xhigh",
} as const;

function gatewayModelCapabilities(provider: string, modelID: string) {
	if (provider !== "openai" || !/^gpt-5\.6-(?:sol|terra|luna)$/.test(modelID))
		return undefined;
	return {
		reasoning: true,
		thinkingLevelMap: GATEWAY_GPT56_THINKING_LEVEL_MAP,
	};
}

// Real context and output ceilings for the models exe.dev ships incomplete
// `limits` for. Regenerate with scripts/probe-gateway-limits.mjs rather
// than editing by hand.
//
// A value is the ceiling the provider itself named and then honoured when we
// asked for exactly it; failing that, the lowest such ceiling another provider
// confirmed for the same model; failing that, the lowest limit a provider
// exe.dev does normalize declares for it. A probe beats a declared limit
// because a declared limit is that provider's own serving cap, not the
// model's. Lowest wins throughout: these providers truncate an oversized
// request instead of rejecting it, so guessing high corrupts answers silently
// while guessing low only wastes budget.
//
// 73 of 96 models resolved against pb-base.exe.xyz.
const PROBED_LIMITS: ReadonlyMap<
	string,
	{ contextWindow?: number; maxTokens?: number }
> = new Map([
	["commandai\0MiniMaxAI/MiniMax-M2.7", { maxTokens: 196608 }],
	["commandai\0MiniMaxAI/MiniMax-M3", { maxTokens: 524288 }],
	["commandai\0Qwen/Qwen3.6-Max-Preview", { maxTokens: 65536 }],
	["commandai\0Qwen/Qwen3.6-Plus", { maxTokens: 65536 }],
	["commandai\0Qwen/Qwen3.7-Flash", { maxTokens: 131072 }],
	["commandai\0Qwen/Qwen3.7-Max", { maxTokens: 131072 }],
	["commandai\0Qwen/Qwen3.7-Plus", { maxTokens: 131072 }],
	["commandai\0Qwen/Qwen3.8-Flash", { maxTokens: 131072 }],
	["commandai\0Qwen/Qwen3.8-Max", { maxTokens: 131072 }],
	["commandai\0claude-fable-5", { maxTokens: 128000 }],
	["commandai\0claude-haiku-4-5-20251001", { maxTokens: 64000 }],
	["commandai\0claude-opus-4-7", { maxTokens: 128000 }],
	["commandai\0claude-opus-4-8", { maxTokens: 128000 }],
	["commandai\0claude-opus-5", { maxTokens: 128000 }],
	["commandai\0claude-sonnet-4-6", { maxTokens: 128000 }],
	["commandai\0claude-sonnet-5", { maxTokens: 128000 }],
	["commandai\0deepseek/deepseek-v4-flash", { maxTokens: 393216 }],
	["commandai\0deepseek/deepseek-v4-flash-vision-exp", { maxTokens: 393216 }],
	["commandai\0deepseek/deepseek-v4-pro", { maxTokens: 393216 }],
	["commandai\0gpt-5.3-codex", { maxTokens: 128000 }],
	["commandai\0gpt-5.4", { maxTokens: 128000 }],
	["commandai\0gpt-5.4-mini", { maxTokens: 128000 }],
	["commandai\0gpt-5.5", { maxTokens: 128000 }],
	["commandai\0gpt-5.6-luna", { maxTokens: 128000 }],
	["commandai\0gpt-5.6-sol", { maxTokens: 128000 }],
	["commandai\0gpt-5.6-terra", { maxTokens: 128000 }],
	["commandai\0minimax/minimax-m2.7-free", { maxTokens: 196608 }],
	["commandai\0minimax/minimax-m3-free", { maxTokens: 524288 }],
	["commandai\0moonshotai/Kimi-K2.6", { maxTokens: 16384 }],
	["commandai\0moonshotai/Kimi-K2.7-Code", { maxTokens: 256000 }],
	["commandai\0moonshotai/Kimi-K3", { maxTokens: 1000000 }],
	["commandai\0poolside/laguna-s-2.1-free", { maxTokens: 32768 }],
	["commandai\0stepfun/Step-3.5-Flash", { contextWindow: 262144 }],
	["commandai\0thinkingmachines/inkling", { maxTokens: 256000 }],
	["commandai\0thinkingmachines/inkling-small", { maxTokens: 262144 }],
	["commandai\0xai/grok-4.5", { maxTokens: 30000 }],
	["commandai\0xai/grok-4.6", { maxTokens: 30000 }],
	["commandai\0xiaomi/mimo-v2.5", { maxTokens: 131072 }],
	["commandai\0xiaomi/mimo-v2.5-pro", { maxTokens: 131072 }],
	["commandai\0z-ai/glm-5.3-flash", { maxTokens: 131072 }],
	["commandai\0zai-org/GLM-5.2", { maxTokens: 131072 }],
	["commandai\0zai-org/GLM-5.3", { maxTokens: 131072 }],
	["opencode-go\0deepseek-v4-flash", { contextWindow: 1000000, maxTokens: 393216 }],
	["opencode-go\0deepseek-v4-flash-vision-exp", { contextWindow: 1000000, maxTokens: 393216 }],
	["opencode-go\0deepseek-v4-pro", { contextWindow: 1000000, maxTokens: 393216 }],
	["opencode-go\0glm-5", { contextWindow: 200000 }],
	["opencode-go\0glm-5.1", { contextWindow: 200000 }],
	["opencode-go\0glm-5.2", { contextWindow: 1000000, maxTokens: 131072 }],
	["opencode-go\0glm-5.3", { contextWindow: 1000000, maxTokens: 131072 }],
	["opencode-go\0glm-5.3-flash", { contextWindow: 1048576, maxTokens: 131072 }],
	["opencode-go\0gpt-5.6-luna", { contextWindow: 1050000, maxTokens: 128000 }],
	["opencode-go\0grok-4.5", { contextWindow: 500000, maxTokens: 30000 }],
	["opencode-go\0grok-4.6", { contextWindow: 500000, maxTokens: 30000 }],
	["opencode-go\0hy3", { contextWindow: 262144 }],
	["opencode-go\0hy4-preview", { contextWindow: 1048576 }],
	["opencode-go\0kimi-k2.5", { contextWindow: 262144 }],
	["opencode-go\0kimi-k2.6", { contextWindow: 262144, maxTokens: 16384 }],
	["opencode-go\0kimi-k2.7-code", { contextWindow: 256000, maxTokens: 256000 }],
	["opencode-go\0kimi-k3", { contextWindow: 1000000, maxTokens: 1000000 }],
	["opencode-go\0longcat-2.0", { maxTokens: 128000 }],
	["opencode-go\0mimo-v2.5", { contextWindow: 1000000, maxTokens: 131072 }],
	["opencode-go\0mimo-v2.5-pro", { contextWindow: 1000000, maxTokens: 131072 }],
	["opencode-go\0minimax-m2.5", { contextWindow: 204800 }],
	["opencode-go\0minimax-m2.7", { contextWindow: 197000, maxTokens: 196608 }],
	["opencode-go\0minimax-m3", { contextWindow: 512000, maxTokens: 512000 }],
	["opencode-go\0muse-spark-1.2-contributor", { contextWindow: 1048576 }],
	["opencode-go\0qwen3.5-plus", { maxTokens: 65536 }],
	["opencode-go\0qwen3.6-plus", { contextWindow: 200000, maxTokens: 65536 }],
	["opencode-go\0qwen3.7-max", { contextWindow: 1000000, maxTokens: 131072 }],
	["opencode-go\0qwen3.7-plus", { contextWindow: 262144, maxTokens: 131072 }],
	["opencode-go\0qwen3.8-flash", { contextWindow: 1000000, maxTokens: 131072 }],
	["opencode-go\0qwen3.8-max", { contextWindow: 1000000, maxTokens: 131072 }],
	["xai\0grok-4.6", { maxTokens: 30000 }],
]);

// The remaining 23 gateway models keep the defaults. Some accept any
// max_tokens and clamp in silence, so their real ceiling never surfaces; the
// rest are off-plan, wrong-protocol, or unavailable, and cannot be asked:
//   commandai/MiniMaxAI/MiniMax-M2.5 (clamps),
//   commandai/Qwen/Qwen3.8-27B (clamps),
//   commandai/google/gemini-3.1-flash-lite, commandai/google/gemini-3.5-flash,
//   commandai/google/gemini-3.5-flash-lite, commandai/google/gemini-3.6-flash,
//   commandai/google/gemini-3.7-flash, commandai/meta/muse-spark-1.1,
//   commandai/meta/muse-spark-1.2, commandai/meta/muse-spark-1.2-contributor,
//   commandai/moonshotai/Kimi-K2.5 (clamps),
//   commandai/moonshotai/Kimi-K2.7-Code-Highspeed (clamps),
//   commandai/nvidia/nemotron-3-ultra-550b-a55b (clamps),
//   commandai/sakana/fugu-ultra, commandai/stepfun/Step-3.7-Flash,
//   commandai/tencent/hy3-paid, commandai/tencent/hy4-preview,
//   commandai/zai-org/GLM-5 (clamps), commandai/zai-org/GLM-5.1 (clamps),
//   commandai/zai-org/GLM-5.2-Fast (clamps), opencode-go/hy3-preview,
//   opencode-go/mimo-v2-omni, opencode-go/mimo-v2-pro

function positiveLimit(value: number | undefined): number | undefined {
	return typeof value === "number" && Number.isFinite(value) && value > 0
		? value
		: undefined;
}

function configFromIntegrationModel(
	integration: DiscoveredIntegration,
	model: IntegrationModel,
	fallback: CatalogModel | undefined,
): ProviderModelConfig | undefined {
	if (!validIntegrationProviderID(model.provider)) return undefined;
	const adapter = integrationAPIAdapter(model);
	if (!adapter) return undefined;
	const baseUrl = integrationProviderBaseURL(
		integration.baseURL,
		model.provider,
		adapter,
	);

	const modelID = integrationModelID(model);
	if (!modelID) return undefined;
	const compat = sanitizeCompat(fallback?.compat, model.provider, modelID);
	const gatewayCapabilities = gatewayModelCapabilities(model.provider, modelID);
	const probed = PROBED_LIMITS.get(`${model.provider}\0${modelID}`);
	return {
		id: modelID,
		name: model.name || fallback?.name || modelID,
		api: adapter.piAPI,
		baseUrl,
		reasoning: fallback?.reasoning ?? gatewayCapabilities?.reasoning ?? false,
		...(fallback?.thinkingLevelMap || gatewayCapabilities?.thinkingLevelMap
			? {
					thinkingLevelMap:
						fallback?.thinkingLevelMap ?? gatewayCapabilities?.thinkingLevelMap,
				}
			: {}),
		input: inputModalities(model, fallback),
		// A probed value outranks the upstream passthrough because it was measured
		// against the endpoint pi actually calls: commandai advertises a 1000000
		// window for stepfun/Step-3.5-Flash and then rejects anything over 262144.
		contextWindow:
			positiveLimit(model.limits?.context_window) ??
			probed?.contextWindow ??
			positiveLimit(model.upstream?.context_length) ??
			fallback?.contextWindow ??
			128000,
		maxTokens:
			positiveLimit(model.limits?.max_output_tokens) ??
			probed?.maxTokens ??
			fallback?.maxTokens ??
			4096,
		cost: fallback?.cost ?? {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		...(compat ? { compat: compat as ProviderModelConfig["compat"] } : {}),
	};
}

type IntegrationModelCandidate = {
	integration: DiscoveredIntegration;
	model: IntegrationModel;
	nativeID: string;
	config: ProviderModelConfig;
};

function integrationModelConfig(
	candidate: IntegrationModelCandidate,
): ProviderModelConfig {
	return {
		...candidate.config,
		id: integrationAliasModelID(candidate.nativeID, candidate.integration.name),
		name: `${candidate.config.name} (${candidate.integration.name})`,
	};
}

function integrationModelNeedsChatGPTPayloadRewrite(
	candidate: IntegrationModelCandidate,
): boolean {
	return (
		candidate.model.exe_dev?.mode === "chatgpt" &&
		candidate.config.api === "openai-responses"
	);
}

export function integrationProviderDisplayName(names: string[]): string {
	const uniq = Array.from(new Set(names)).sort();
	if (uniq.length === 0) return "llm";
	if (uniq.length <= 2) return uniq.join(", ");
	return `${uniq[0]} + ${uniq.length - 1} more`;
}

export function integrationPromptAvailabilityLabel(names: string[]): string {
	const uniq = Array.from(new Set(names)).sort();
	if (uniq.length <= 2) return uniq.join(", ");
	return `${uniq.slice(0, 2).join(", ")}, ...`;
}

export function providerInfosFromIntegrationCatalogs(
	integrations: DiscoveredIntegration[],
	pricingCatalog: Catalog | undefined,
	warn: WarnFn = console.warn,
): Map<string, IntegrationProviderInfo> {
	const costs = costCatalogIndex(pricingCatalog);
	const grouped = new Map<
		string,
		{ names: string[]; candidates: IntegrationModelCandidate[] }
	>();
	const warnedMissingPricing = new Set<string>();

	for (const integration of integrations) {
		if (!integration.catalog) continue;
		for (const model of integration.catalog.models) {
			const provider = model.provider;
			const modelID = integrationModelID(model);
			if (!modelID) continue;
			const fallback = fallbackCatalogModel(costs, provider, modelID, model.id);
			const config = configFromIntegrationModel(integration, model, fallback);
			if (!config) continue;
			if (!hasPricing(fallback))
				warnedMissingPricing.add(`${provider}/${modelID}`);

			let entry = grouped.get(provider);
			if (!entry) {
				entry = { names: [], candidates: [] };
				grouped.set(provider, entry);
			}
			entry.names.push(integration.name);
			entry.candidates.push({ integration, model, nativeID: modelID, config });
		}
	}

	if (warnedMissingPricing.size === 1) {
		const [model] = warnedMissingPricing;
		warn(
			`[pi-exe-dev] missing pricing for integration model ${model}; pi usage cost will be reported as zero`,
		);
	} else if (warnedMissingPricing.size > 1) {
		warn(
			`[pi-exe-dev] missing pricing for ${warnedMissingPricing.size} integration models; pi usage cost will be reported as zero`,
		);
	}

	const out = new Map<string, IntegrationProviderInfo>();
	for (const [provider, entry] of grouped) {
		const models: ProviderModelConfig[] = [];
		const modelAliases = new Map<string, string>();
		const chatGPTModelIds = new Set<string>();
		for (const candidate of entry.candidates) {
			const modelConfig = integrationModelConfig(candidate);
			models.push(modelConfig);
			modelAliases.set(modelConfig.id, candidate.nativeID);
			if (integrationModelNeedsChatGPTPayloadRewrite(candidate)) {
				chatGPTModelIds.add(modelConfig.id);
			}
		}
		const first = models[0];
		if (!first?.baseUrl) continue;
		const config: ProviderConfig = {
			name: integrationProviderDisplayName(entry.names),
			baseUrl: first.baseUrl,
			apiKey: "integration",
			models,
		};
		out.set(
			`exe-dev-${provider}`,
			integrationProviderInfo(config, {
				modelAliases: modelAliases.size > 0 ? modelAliases : undefined,
				chatGPTModelIds: chatGPTModelIds.size > 0 ? chatGPTModelIds : undefined,
			}),
		);
	}
	return out;
}

// sanitizeCompat copies only fields whose values pi-ai understands. Unknown
// values would misconfigure the model silently; dropping them lets pi-ai fall
// back to its URL-based auto-detection. Returns undefined if nothing is set.
function sanitizeCompat(
	c: CatalogCompat | undefined,
	providerId: string,
	modelId: string,
): CompatBag | undefined {
	if (!c) return undefined;
	const out: CompatBag = {};
	if (typeof c.supportsDeveloperRole === "boolean")
		out.supportsDeveloperRole = c.supportsDeveloperRole;
	if (typeof c.supportsReasoningEffort === "boolean")
		out.supportsReasoningEffort = c.supportsReasoningEffort;
	if (c.maxTokensField) {
		if (KNOWN_MAX_TOKENS_FIELDS.has(c.maxTokensField)) {
			out.maxTokensField = c.maxTokensField as CompatBag["maxTokensField"];
		} else {
			console.warn(
				`[pi-exe-dev] dropping unknown maxTokensField "${c.maxTokensField}" on ${providerId}/${modelId}`,
			);
		}
	}
	if (c.thinkingFormat) {
		if (KNOWN_THINKING_FORMATS.has(c.thinkingFormat)) {
			out.thinkingFormat = c.thinkingFormat as CompatBag["thinkingFormat"];
		} else {
			console.warn(
				`[pi-exe-dev] dropping unknown thinkingFormat "${c.thinkingFormat}" on ${providerId}/${modelId}`,
			);
		}
	}
	if (c.cacheControlFormat) {
		if (KNOWN_CACHE_CONTROL_FORMATS.has(c.cacheControlFormat)) {
			out.cacheControlFormat =
				c.cacheControlFormat as CompatBag["cacheControlFormat"];
		} else {
			console.warn(
				`[pi-exe-dev] dropping unknown cacheControlFormat "${c.cacheControlFormat}" on ${providerId}/${modelId}`,
			);
		}
	}
	return Object.keys(out).length > 0 ? out : undefined;
}

function managedBaseUrls(config: ProviderConfig): ReadonlySet<string> {
	const out = new Set<string>();
	if (config.baseUrl) out.add(config.baseUrl);
	for (const model of config.models ?? []) {
		if (model.baseUrl) out.add(model.baseUrl);
	}
	return out;
}

function integrationProviderInfo(
	config: ProviderConfig,
	rewrite?: Omit<IntegrationProviderPayloadRewrite, "selectedModelID">,
): IntegrationProviderInfo {
	return {
		config,
		modelAliases: rewrite?.modelAliases,
		chatGPTModelIds: rewrite?.chatGPTModelIds,
		baseUrls: managedBaseUrls(config),
	};
}
